# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 14:01
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EloVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('num_games', models.PositiveIntegerField(default=0)),
                ('elo', models.FloatField(default=1200.0)),
            ],
        ),
        migrations.CreateModel(
            name='GameSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(regex='^\\d+ (Red|Blue|White|Yellow|Green|Rainbow) \\d+(,\\d+ (Red|Blue|White|Yellow|Green|Rainbow) \\d+)*$')])),
                ('num_players', models.PositiveIntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('score', models.PositiveIntegerField()),
                ('lives', models.PositiveIntegerField(blank=True, null=True)),
                ('hints', models.PositiveIntegerField(blank=True, null=True)),
                ('num_turns', models.PositiveIntegerField(blank=True, null=True)),
                ('game_setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.GameSetup')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.Entity')),
            ],
            bases=('game.entity',),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.Entity')),
            ],
            bases=('game.entity',),
        ),
        migrations.AddField(
            model_name='elovariation',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Entity'),
        ),
        migrations.AddField(
            model_name='elovariation',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Result'),
        ),
        migrations.CreateModel(
            name='AI',
            fields=[
                ('team_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.Team')),
                ('ai_name', models.CharField(max_length=200)),
                ('ai_params', jsonfield.fields.JSONField(default=dict)),
                ('fixed_elo', models.FloatField(blank=True, default=None, null=True)),
            ],
            bases=('game.team',),
        ),
        migrations.AddField(
            model_name='result',
            name='players',
            field=models.ManyToManyField(to='game.Player'),
        ),
        migrations.AddField(
            model_name='result',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Team'),
        ),
    ]
