# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 11:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_deck_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(regex='^\\d+ (Red|Blue|White|Yellow|Green|Rainbow) \\d+(,\\d+ (Red|Blue|White|Yellow|Green|Rainbow) \\d+)*$')])),
                ('num_players', models.PositiveIntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Game',
            new_name='Result',
        ),
        migrations.DeleteModel(
            name='Deck',
        ),
        migrations.AlterField(
            model_name='result',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.GameSetup'),
        ),
    ]
