# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 12:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20170112_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI',
            fields=[
                ('team_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.Team')),
                ('ai_name', models.CharField(max_length=200)),
                ('ai_params', picklefield.fields.PickledObjectField(editable=False)),
                ('fixed_elo', models.FloatField(blank=True, default=None, null=True)),
            ],
            bases=('game.team',),
        ),
        migrations.AddField(
            model_name='result',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
