# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 13:05
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20170112_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai',
            name='ai_params',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
