# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20170112_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='type',
        ),
    ]
