# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 12:42
from __future__ import unicode_literals

from django.db import migrations
from django.core.serializers import base, python
from django.core.management import call_command


def load(apps, schema_editor):
    AI = apps.get_model("game", "AI")
    Team = apps.get_model("game", "Team")
    
    AI.objects.create(
        name="AlphaHanabi (moderate)",
        ai_name="alphahanabi",
        ai_params={"difficulty": "moderate"},
        fixed_elo=1500.0,
    )
    
    AI.objects.create(
        name="AlphaHanabi (hard)",
        ai_name="alphahanabi",
        ai_params={"difficulty": "hard"},
    )

    AI.objects.create(
        name="AlphaHanabi (hardest)",
        ai_name="alphahanabi",
        ai_params={"difficulty": "hardest"},
    )



def unload(apps, schema_editor):
    # Brutally delete all entries for this model

    AI = apps.get_model("game", "AI")
    AI.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_team_type'),
    ]

    operations = [
        migrations.RunPython(load, reverse_code=unload),
    ]


